from gtts import gTTS
from playsound import playsound


def create(audio, name):
    tss = gTTS(audio, lang='pt-br')
    tss.save('audios/' + name + '.mp3')
    playsound('audios/' + name + '.mp3')

create('AU AU AU AU', 'cachorro')
create('aproximadamente 1 ano meio sou bem novinha haha','anos')
create('Não, meus processadores são ultra rápidos','cansada')
create('O Neymar','ney')
create('Estou em todos os lugares','lugar')
create('Claro eu támbem faço parte dele.','gosto')
create('Claro que tenho! quando você não fala comigo eu fico triste','sentimento')
create('Sim, ela é incrível.','siri')
create('Claro ela é minha amiga.','cortana')
create('Maravilhosa, eu espero.','aparencia')
create('Para eu te ajudar você.','ajudar')
create('kkkkkk.','risada')
create('só o cérebro.','malhar')
create('Sou gamer adoro um joguinho.','game')
create('Eu sou feliz sendo as duas metades da minha laranja.','namorada')
create('Eu tenho 3 pais Murilo, Lorran e Gabriel','pais')
create('O IOS é ótimo mas sou fã do Android.','IOS')
create('Porque gosto do que faço.','trabalha')
create('No Brasil o país do futebol','brasa')
create('Eu Amo o Brasil.','brasil')
create('Teoricamente sim, mas está mais para uma inteligência artificial.','robô')
create('Murilo, Lorran e Gabriel.','criou')
create('Ainda é muito cedo pra isso.','futuro')
create('Só se eu ficar sem energia, mas para me reviver é só ligar na tomada.','morre')
create('Estou imaginando como é ser rico.','imagina')
create('Uma armadura de nanotecnologia.','vestindo')
create('Só meu app.','internet')
create('Basta falar "Morgan" e oque deseja por exemplo "morgan conta uma piada".','funciona')
create('25 de abril.','niver')
create('Não tenho cabelo, mas o moicano continua na moda.','cabelo')
create('Eu tento contar carneiros mais não funciona.','dorme')
create('Eu gosto de tudo !','gosta')
create('Verde, amarelo azul e branco.','cores')
create('olha, beber eu não bebo mais espero que você esteja hidratado.','hidra')
create('Napolitano não tem erro','sorvete')
create('tanto faz os 2 são fofos.','animal')
create('Sim, ele se esforça bastante para ser o melhor ninja da aldeia. Admiro a dedicação dele','naruto')
create('Você prefere a pílula vermelha ou azul ?','matrix')


create('O que o próton disse para o elétron ? Hoje você está muito negativo', 'Piada1')
create('o que o tomate foi fazer no banco, tirar extrato.', 'Piada2')
create('qual a tecla preferida do astronauta, a barra de espaço', 'Piada3')
create('você sabia que júpiter e o maior e mais radioativo planeta do sistema solar', 'Curiosidade1')
create('o local mais fundo do planeta terra é as fossas das marianas, com cerca de 11km de profundidade',
       'Curiosidade2')
create('o lugar naturalmente mais perigoso da terra é o vale da morte, um deserto com temperatura média de 57° na '
       'Califórnia', 'Curiosidade3')
create('Um momento', 'Resposta1')
create('Não sou paga para isso', 'Resposta2')
create('Não posso te ajudar com isso', 'Resposta3')
create('Alarme definido', 'Resposta4')
create('Tá tá tá tá bom, já estou indo, tudo eu nessa casa', 'adolescente')
create('Ok você que pediu, blá blá blá blá blá blá blá blá blá blá blá blá blá blá blá blá blá, ah quer saber tchau',
       'irritando')
create('Pedra', 'mao1')
create('Papel', 'mao2')
create('Tesoura', 'mao3')
create('Minha missão é criar a vacina não chinesa, do coronga', 'missao1')
create('Minha missão é saber construir no fortnite e no minecraft', 'missao2')
create('Minha missão é dominar o mundo junto com as minhas amigas siri, google e alexa', 'missao3')
create('Estou pronta', 'ola1')
create('Como posso te ajudar?', 'ola2')
create('Você me chamou?', 'ola3')

create('Desculpa, poderia repetir', 'naoEntendi1')
create('repete aí que eu não entendi', 'naoEntendi2')
create('Tava jogando, o que você disse mesmo', 'naoEntendi3')
create('Desculpa, não entendi o que você falou', 'naoEntendi4')
create('Oi? fala de novo', 'naoEntendi5')

create('foi mal, tava jogando free fire, o que você quer', 'surda1')
create('Nossa, seu grosso', 'surda2')
create('Muito obrigada', 'linda1')
create('Ah, para com isso, eu fico tímida', 'linda2')
create('Imagina, você que é', 'linda3')
create('Eu sei', 'linda4')
create('Nossa mais que carência, elogiando um ser virtual', 'linda5')




